# Site settings
title: jericson&mdash;Community Manager
email: jericson@stackexchange.com
description: > # this means to ignore newlines until "baseurl:"
  Jon Ericson works for Stack Exchange as a Community Manager. What is a Community Manager? Read on.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://jericson.github.io/" # the base hostname & protocol for your site
twitter_username: jlericson
github_username:  jericson

# Build settings
markdown: kramdown
