# Site settings
title: Jon Quixote
name: Jon Quixote
icon: /images/donquixote.gif

description: > # this means to ignore newlines until "baseurl:"
  In which the author considers whether a community is more like a giant or more like a windmill.
#baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jlericson.com" # the base hostname & protocol for your site
author:
  name: Jon Ericson
  email: jon@jlericson.com
#author_url: https://meta.stackexchange.com/users/1438/jon-ericson
#rss: RSS feed

#GA 
google_analytics: G-84N1KC6S9M

# SEO


logo: /images/donquixote.gif 

defaults:
  -
    values:
      author: Jon Ericson


# Build settings
#markdown: kramdown
markdown: CommonMarkGhPages
encoding: utf-8
include: [.emacs, "/.well-known"]

#theme: minima
remote_theme: jekyll/minima

minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/jericson" }
    - { platform: mastodon, user_url: "https://infosec.exchange/@jericson" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/jonericson/" }
    - { platform: twitter, user_url: "https://x.com/jlericson" }
    - { platform: facebook, user_url: "https://www.facebook.com/jlericson" }
    - { platform: bluesky, user_url: "https://bsky.app/profile/jlericson.com" }
    - { platform: devto, user_url: "https://dev.to/jericson" }
    - { platform: keybase, user_url: "https://keybase.io/jericson/" }
    - { platform: stackoverflow, user_url: "https://stackoverflow.com/users/1438/jon-ericson" }

# Why does this fail?
#exclude: [tmp]

liquid:
  error_mode: warn

commonmark:
  options: ["FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

# Tags (https://github.com/pattex/jekyll-tagging)
tag_page_layout: tag_page
tag_page_dir: tag
#tag_feed_layout: tag_feed
#tag_feed_dir: tag

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-titles-from-headings
  - jekyll-feed
  - jekyll-remote-theme

#safe: true

titles_from_headings:
  enabled:     false
  strip_title: false
  collections: false

# LocalWords:  jericson LocalWords kramdown herf ericson http
# LocalWords:  jlericson dir
