# Site settings
title: Jon Quixote
name: Jon Quixote
icon: /images/donquixote.gif
email: jon@jlericson.com
description: > # this means to ignore newlines until "baseurl:"
  In which the author considers whether a community is more like a giant or more like a windmill.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jlericson.com" # the base hostname & protocol for your site
author: Jon Ericson
author_url: http://meta.stackexchange.com/users/1438/jon-ericson
twitter_username: jlericson
github_username:  jericson

defaults:
  -
    values:
      author: Jon Ericson


# Build settings
#markdown: kramdown
markdown: CommonMarkGhPages
encoding: utf-8
include: [.emacs]

liquid:
  error_mode: warn

commonmark:
  options: ["FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

# Tags (https://github.com/pattex/jekyll-tagging)
tag_page_layout: tag_page
tag_page_dir: tag
#tag_feed_layout: tag_feed
#tag_feed_dir: tag

# LocalWords:  jericson LocalWords kramdown herf ericson http
# LocalWords:  jlericson dir
