# Site settings
title: Pathological Writer
email: jericson@stackexchange.com
description: > # this means to ignore newlines until "baseurl:"
  Community Manager at Stack Exchange. What's a Community Manager?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jericson.github.io/" # the base hostname & protocol for your site
author: Jon Ericson
twitter_username: jlericson
github_username:  jericson

defaults:
  -
    values:
      author: Jon Ericson


# Build settings
markdown: kramdown
