# Site settings
title: Pathological Writer
email: jericson@stackexchange.com
description: > # this means to ignore newlines until "baseurl:"
  Jon Ericson works for Stack Exchange as a Community Manager. What is a Community Manager? I'm still trying to figure that out.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jericson.github.io/" # the base hostname & protocol for your site
author: Jon Ericson
twitter_username: jlericson
github_username:  jericson

# Build settings
markdown: kramdown
